export enum ABILITY_EFFECTS {
    NONE = 'NONE',
    CROWD_CONTROL = 'CROWD_CONTROL',
    TM_MANIPULATION = 'TM_MANIPULATION',
    EXTRA_TURN = 'EXTRA_TURN',
    SPEED_MANIPULATION = 'SPEED_MANIPULATION',
    AURA_SPEED = 'AURA_SPEED'
}
export enum ABILITY_EFFECT_TARGET {
    PLAYER_TEAM = 'PLAYER_TEAM',
    OPPONENT_TEAM = 'OPPONENT_TEAM',
    SELF = 'SELF',
    TARGET = 'TARGET',
    NONE = 'NONE',
}
export enum TM_MANIPULATION_TYPES {
    GAIN,
    REMOVE
}

export enum SPEED_MANIPULATION_TYPES {
    ADD,
    remove,
}

export enum CROWD_CONTROL_TYPES {
    SLEEP,
    FREEZE,
    STUN
}

export enum PRIORITY_TYPES {
    LOWER,
    MIDIUM,
    HIGH,
    MAX
}